### ISSUE TITLE
企图更改已连接边的位置时   无法修改还会报错

### ISSUE THREAD

**Issue by chenganghub** [keydone/g6-graph#35]
anchor-event.js:63 Uncaught TypeError: Cannot read properties of undefined (reading 'get')
    at Circle.<anonymous> (anchor-event.js:63:29)
    at doEmit (index.js:61:1)
    at Circle.push../node_modules/@antv/event-emitter/esm/index.js.EventEmitter.emit (index.js:64:1)
    at emitTargetEvent (event-contoller.js:44:1)
    at EventController.push../node_modules/@antv/g-base/esm/event/event-contoller.js.EventController._emitEvent (event-contoller.js:403:1)
    at EventController.push../node_modules/@antv/g-base/esm/event/event-contoller.js.EventController._onmousemove (event-contoller.js:346:1)
    at EventController.push../node_modules/@antv/g-base/esm/event/event-contoller.js.EventController._triggerEvent (event-contoller.js:197:1)
    at HTMLCanvasElement.EventController._eventCallback (event-contoller.js:89:1)

**Comment by claudewowo** [comment]
如何修改的? 有没有案例代码

**Comment by chenganghub** [comment]
1.两个节点之间已经连线 2.去修改连线的位置

**Comment by claudewowo** [comment]
请附上在线 demo

**Comment by chenganghub** [comment]
我就是下载的源码   没有做任何修改    操作哈就出来了

**Comment by chenganghub** [comment]
正在找复现路径

**Comment by chenganghub** [comment]
![image](https://user-images.githubusercontent.com/42639553/156525208-770adb04-882a-4df0-a1bd-78956e0cea77.png)

**Comment by claudewowo** [comment]
这里加了 tooltip, 鼠标向右拖拽会被 tooltip 阻断事件, 这个 demo 中添加的线没法更改连线, 只能添加, 正常情况下需要在鼠标拖拽时隐藏 tooltip, demo 里没写而已

**Comment by chenganghub** [comment]
现在  在报错  请问哈在哪里处理啊

**Comment by claudewowo** [comment]
这个 demo 不是完整项目, demo 里可以直接关了 tooltip

**Comment by chenganghub** [comment]
谢谢

**Comment by chenganghub** [comment]
不好意思  在请教哈  有没有  获取已编辑的数据接口

**Comment by claudewowo** [comment]
有个 save 方法, 多看官方文档
