### ISSUE TITLE
执行npm run dev报错

### ISSUE THREAD

**Issue by XuYaoAnansi** [keydone/g6-graph#37]
/Users/anansi/vscodecode/webflow/welabx-g6/node_modules/webpack-merge/dist/index.js:63
            throw new TypeError("Merging undefined is not supported");
            ^

TypeError: Merging undefined is not supported
    at mergeWithOptions (/Users/anansi/vscodecode/webflow/welabx-g6/node_modules/webpack-merge/dist/index.js:63:19)
    at merge (/Users/anansi/vscodecode/webflow/welabx-g6/node_modules/webpack-merge/dist/index.js:52:35)
    at Object.<anonymous> (/Users/anansi/vscodecode/webflow/welabx-g6/webpack/webpack.dev.js:45:18)

**Comment by claudewowo** [comment]
已支持 npm7+ 运行
